# MINI_PROJET1 : PANDAS

Utilisation du dataset IMDb Top 1000 Movies de Kaggle.

Niveau 1 : Sélection et filtrage
Afficher uniquement les films sortis après 2015.
Afficher uniquement les films d'action.
Afficher les films ayant une note IMDb supérieure à 8.
Afficher les films sortis entre 2010 et 2020.
Afficher les films dont le réalisateur est Christopher Nolan.


Niveau 2 : Tri
Trouver les 10 films les mieux notés.
Trouver les 10 films les plus rentables.
Trouver les 20 films les plus récents.
Trouver le film le plus long.
Trouver le film le moins bien noté.


Niveau 3 : Valeurs manquantes
Combien de lignes contiennent au moins une valeur manquante ?
Quelle colonne contient le plus de valeurs manquantes ?
Remplacer les recettes manquantes par 0.
Afficher uniquement les films dont le Metascore est manquant.


Niveau 4 : Groupby
Combien de films par année ?
Combien de films par réalisateur ?
Quelle est la note IMDb moyenne par réalisateur ?
Quelle est la note IMDb moyenne par genre ?
Quel réalisateur possède le plus de films dans le dataset ?
Quelle année possède la meilleure note moyenne ?


Niveau 5 : Value Counts
Quels sont les genres les plus fréquents ?
Quels sont les 10 réalisateurs les plus présents ?
Quelle année apparaît le plus souvent ?


Niveau 6 : Création de colonnes
Créer une colonne indiquant si un film est :
Court (< 90 min)
Moyen (90-120 min)
Long (> 120 min)
Créer une colonne "Décennie".
Créer une colonne indiquant si un film est "Très bien noté" (IMDb ≥ 8).


Niveau 7 : MultiIndex
Combien de films par année et par genre ?
Quelle est la note moyenne par année et par réalisateur ?
Quel genre domine chaque décennie ?


Niveau 8 : Réflexion
Les critiques (Metascore) sont-elles généralement plus sévères que les utilisateurs (IMDb) ?
Les films longs sont-ils mieux notés que les films courts ?
Les réalisateurs avec beaucoup de films obtiennent-ils de meilleures notes en moyenne ?
Certaines décennies produisent-elles davantage de films bien notés ?
Le genre le plus fréquent est-il aussi le mieux noté ?


Ces exercices couvrent presque tout ce que tu viens d'apprendre en Pandas : filtrage, loc, iloc, groupby, value_counts, sort_values, apply, fillna, isnull, set_index, MultiIndex et création de colonnes.

In [1]:
import pandas as pd

In [2]:
#Chargement du Dataset dans le notebook

movies = pd.read_csv('imdb_top_1000.csv')
movies

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

In [4]:
# Changer le type de la colonne Gross

movies.Gross = movies.Gross.str.replace(',', '', regex=False)
movies.Gross = pd.to_numeric(movies.Gross, errors='coerce')

In [6]:
#Changer le type de la colonne Released_Year
movies.Released_Year = pd.to_numeric(movies.Released_Year, errors='coerce')
movies.Released_Year = movies.Released_Year.astype('Int64')

In [8]:
#Changer le type de la colonne Runtime
movies.Runtime = movies.Runtime.str.replace('min', '', regex=False)
movies.Runtime = pd.to_numeric(movies.Runtime, errors='coerce')

## Afficher uniquement les films sortis après 2015.

In [10]:
movies['Released_Year'].dtype
movies[movies.Released_Year >= 2015]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
18,https://m.media-amazon.com/images/M/MV5BNjViNW...,Hamilton,2020,PG-13,160,"Biography, Drama, History",8.6,The real life of one of America's foremost fou...,90.0,Thomas Kail,Lin-Manuel Miranda,Phillipa Soo,Leslie Odom Jr.,Renée Elise Goldsberry,55291,NaN
19,https://m.media-amazon.com/images/M/MV5BYWZjMj...,Gisaengchung,2019,A,132,"Comedy, Drama, Thriller",8.6,Greed and class discrimination threaten the ne...,96.0,Bong Joon Ho,Kang-ho Song,Lee Sun-kyun,Cho Yeo-jeong,Choi Woo-sik,552778,53367844.0
20,https://m.media-amazon.com/images/M/MV5BOTc2ZT...,Soorarai Pottru,2020,U,153,Drama,8.6,"Nedumaaran Rajangam ""Maara"" sets out to make t...",NaN,Sudha Kongara,Suriya,Madhavan,Paresh Rawal,Aparna Balamurali,54995,NaN
33,https://m.media-amazon.com/images/M/MV5BNGVjNW...,Joker,2019,A,122,"Crime, Drama, Thriller",8.5,"In Gotham City, mentally troubled comedian Art...",59.0,Todd Phillips,Joaquin Phoenix,Robert De Niro,Zazie Beetz,Frances Conroy,939252,335451311.0
53,https://m.media-amazon.com/images/M/MV5BMmExNz...,Capharnaüm,2018,A,126,Drama,8.4,While serving a five-year sentence for a viole...,75.0,Nadine Labaki,Zain Al Rafeea,Yordanos Shiferaw,Boluwatife Treasure Bankole,Kawsar Al Haddad,62635,1661096.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
892,https://m.media-amazon.com/images/M/MV5BMjI4Mz...,Moana,2016,U,107,"Animation, Adventure, Comedy",7.6,"In Ancient Polynesia, when a terrible curse in...",81.0,Ron Clements,John Musker,Don Hall,Chris Williams,Auli'i Cravalho,272784,248757044.0
893,https://m.media-amazon.com/images/M/MV5BMjA5Nj...,Sicario,2015,A,121,"Action, Crime, Drama",7.6,An idealistic FBI agent is enlisted by a gover...,82.0,Denis Villeneuve,Emily Blunt,Josh Brolin,Benicio Del Toro,Jon Bernthal,371291,46889293.0
894,https://m.media-amazon.com/images/M/MV5BNmZkYj...,Creed,2015,A,133,"Drama, Sport",7.6,The former World Heavyweight Champion Rocky Ba...,82.0,Ryan Coogler,Michael B. Jordan,Sylvester Stallone,Tessa Thompson,Phylicia Rashad,247666,109767581.0
896,https://m.media-amazon.com/images/M/MV5BMTg4ND...,Hell or High Water,2016,R,102,"Action, Crime, Drama",7.6,A divorced father and his ex-con older brother...,88.0,David Mackenzie,Chris Pine,Ben Foster,Jeff Bridges,Gil Birmingham,204175,26862450.0
903,https://m.media-amazon.com/images/M/MV5BNmE5Zm...,A Star Is Born,2018,UA,136,"Drama, Music, Romance",7.6,A musician helps a young singer find fame as a...,88.0,Bradley Cooper,Lady Gaga,Bradley Cooper,Sam Elliott,Greg Grunberg,334312,215288866.0

## Afficher uniquement les films d'action

In [12]:
movies.Genre.dtype
movies[movies.Genre.str.contains('Action')]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444.0
5,https://m.media-amazon.com/images/M/MV5BNzA5ZD...,The Lord of the Rings: The Return of the King,2003,U,201,"Action, Adventure, Drama",8.9,Gandalf and Aragorn lead the World of Men agai...,94.0,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,1642758,377845905.0
8,https://m.media-amazon.com/images/M/MV5BMjAxMz...,Inception,2010,UA,148,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,74.0,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,2067042,292576195.0
10,https://m.media-amazon.com/images/M/MV5BN2EyZj...,The Lord of the Rings: The Fellowship of the Ring,2001,U,178,"Action, Adventure, Drama",8.8,A meek Hobbit from the Shire and eight compani...,92.0,Peter Jackson,Elijah Wood,Ian McKellen,Orlando Bloom,Sean Bean,1661481,315544750.0
13,https://m.media-amazon.com/images/M/MV5BZGMxZT...,The Lord of the Rings: The Two Towers,2002,UA,179,"Action, Adventure, Drama",8.7,While Frodo and Sam edge closer to Mordor with...,87.0,Peter Jackson,Elijah Wood,Ian McKellen,Viggo Mortensen,Orlando Bloom,1485555,342551365.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968,https://m.media-amazon.com/images/M/MV5BYjcxMz...,Falling Down,1993,R,113,"Action, Crime, Drama",7.6,An ordinary man frustrated with the various fl...,56.0,Joel Schumacher,Michael Douglas,Robert Duvall,Barbara Hershey,Rachel Ticotin,171640,40903593.0
979,https://m.media-amazon.com/images/M/MV5BZTllNW...,Lethal Weapon,1987,A,109,"Action, Crime, Thriller",7.6,Two newly paired cops who are complete opposit...,68.0,Richard Donner,Mel Gibson,Danny Glover,Gary Busey,Mitchell Ryan,236894,65207127.0
982,https://m.media-amazon.com/images/M/MV5BN2VlNj...,Mad Max 2,1981,A,96,"Action, Adventure, Sci-Fi",7.6,"In the post-apocalyptic Australian wasteland, ...",77.0,George Miller,Mel Gibson,Bruce Spence,Michael Preston,Max Phipps,166588,12465371.0
983,https://m.media-amazon.com/images/M/MV5BYTU2MW...,The Warriors,1979,UA,92,"Action, Crime, Thriller",7.6,"In the near future, a charismatic leader summo...",65.0,Walter Hill,Michael Beck,James Remar,Dorsey Wright,Brian Tyler,93878,22490039.0
985,https://m.media-amazon.com/images/M/MV5BNDQ3Mz...,Escape from Alcatraz,1979,A,112,"Action, Biography, Crime",7.6,Alcatraz is the most secure prison of its time...,76.0,Don Siegel,Clint Eastwood,Patrick McGoohan,Roberts Blossom,Jack Thibeau,121731,43000000.0

## Afficher les films ayant une note IMDb supérieure à 8

In [13]:
movies.IMDB_Rating.dtype
movies[movies.IMDB_Rating >= 8]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469.0
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,134966411.0
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444.0
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,57300000.0
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,4360000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458,https://m.media-amazon.com/images/M/MV5BNjUyMT...,The Wizard of Oz,1939,U,102,"Adventure, Family, Fantasy",8.0,Dorothy Gale is swept away from a farm in Kans...,92.0,Victor Fleming,George Cukor,Mervyn LeRoy,Norman Taurog,Richard Thorpe,371379,2076020.0
459,https://m.media-amazon.com/images/M/MV5BYTE4Nj...,La règle du jeu,1939,NaN,110,"Comedy, Drama",8.0,A bourgeois life in France at the onset of Wor...,NaN,Jean Renoir,Marcel Dalio,Nora Gregor,Paulette Dubost,Mila Parély,26725,NaN
460,https://m.media-amazon.com/images/M/MV5BYmFlOW...,The Thin Man,1934,TV-PG,91,"Comedy, Crime, Mystery",8.0,Former detective Nick Charles and his wealthy ...,86.0,W.S. Van Dyke,William Powell,Myrna Loy,Maureen O'Sullivan,Nat Pendleton,26642,NaN
461,https://m.media-amazon.com/images/M/MV5BMzg2MW...,All Quiet on the Western Front,1930,U,152,"Drama, War",8.0,"A German youth eagerly enters World War I, but...",91.0,Lewis Milestone,Lew Ayres,Louis Wolheim,John Wray,Arnold Lucy,57318,3270000.0
462,https://m.media-amazon.com/images/M/MV5BMTEyMT...,Bronenosets Potemkin,1925,NaN,75,"Drama, History, Thriller",8.0,In the midst of the Russian Revolution of 1905...,97.0,Sergei M. Eisenstein,Aleksandr Antonov,Vladimir Barskiy,Grigoriy Aleksandrov,Ivan Bobrov,53054,50970.0

##  Afficher les films sortis entre 2010 et 2020

In [14]:
movies[(movies.Released_Year >= 2010) & (movies.Released_Year <= 2020)]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
8,https://m.media-amazon.com/images/M/MV5BMjAxMz...,Inception,2010,UA,148,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,74.0,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,2067042,292576195.0
18,https://m.media-amazon.com/images/M/MV5BNjViNW...,Hamilton,2020,PG-13,160,"Biography, Drama, History",8.6,The real life of one of America's foremost fou...,90.0,Thomas Kail,Lin-Manuel Miranda,Phillipa Soo,Leslie Odom Jr.,Renée Elise Goldsberry,55291,NaN
19,https://m.media-amazon.com/images/M/MV5BYWZjMj...,Gisaengchung,2019,A,132,"Comedy, Drama, Thriller",8.6,Greed and class discrimination threaten the ne...,96.0,Bong Joon Ho,Kang-ho Song,Lee Sun-kyun,Cho Yeo-jeong,Choi Woo-sik,552778,53367844.0
20,https://m.media-amazon.com/images/M/MV5BOTc2ZT...,Soorarai Pottru,2020,U,153,Drama,8.6,"Nedumaaran Rajangam ""Maara"" sets out to make t...",NaN,Sudha Kongara,Suriya,Madhavan,Paresh Rawal,Aparna Balamurali,54995,NaN
21,https://m.media-amazon.com/images/M/MV5BZjdkOT...,Interstellar,2014,UA,169,"Adventure, Drama, Sci-Fi",8.6,A team of explorers travel through a wormhole ...,74.0,Christopher Nolan,Matthew McConaughey,Anne Hathaway,Jessica Chastain,Mackenzie Foy,1512360,188020017.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
906,https://m.media-amazon.com/images/M/MV5BMTY3Nj...,Despicable Me,2010,U,95,"Animation, Comedy, Crime",7.6,When a criminal mastermind uses a trio of orph...,72.0,Pierre Coffin,Chris Renaud,Steve Carell,Jason Segel,Russell Brand,500851,251513985.0
907,https://m.media-amazon.com/images/M/MV5BNjg3OD...,50/50,2011,R,100,"Comedy, Drama, Romance",7.6,"Inspired by a true story, a comedy centered on...",72.0,Jonathan Levine,Joseph Gordon-Levitt,Seth Rogen,Anna Kendrick,Bryce Dallas Howard,315426,35014192.0
908,https://m.media-amazon.com/images/M/MV5BMTMzNz...,Kick-Ass,2010,UA,117,"Action, Comedy, Crime",7.6,Dave Lizewski is an unnoticed high school stud...,66.0,Matthew Vaughn,Aaron Taylor-Johnson,Nicolas Cage,Chloë Grace Moretz,Garrett M. Brown,524081,48071303.0
910,https://m.media-amazon.com/images/M/MV5BMjAxOT...,Moneyball,2011,PG-13,133,"Biography, Drama, Sport",7.6,Oakland A's general manager Billy Beane's succ...,87.0,Bennett Miller,Brad Pitt,Robin Wright,Jonah Hill,Philip Seymour Hoffman,369529,75605492.0
911,https://m.media-amazon.com/images/M/MV5BYmFmNj...,La piel que habito,2011,R,120,"Drama, Horror, Thriller",7.6,"A brilliant plastic surgeon, haunted by past t...",70.0,Pedro Almodóvar,Antonio Banderas,Elena Anaya,Jan Cornet,Marisa Paredes,138959,3185812.0

## Afficher les films dont le réalisateur est Christopher Nolan

In [15]:
movies[movies.Director == 'Christopher Nolan']

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444.0
8,https://m.media-amazon.com/images/M/MV5BMjAxMz...,Inception,2010,UA,148,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,74.0,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,2067042,292576195.0
21,https://m.media-amazon.com/images/M/MV5BZjdkOT...,Interstellar,2014,UA,169,"Adventure, Drama, Sci-Fi",8.6,A team of explorers travel through a wormhole ...,74.0,Christopher Nolan,Matthew McConaughey,Anne Hathaway,Jessica Chastain,Mackenzie Foy,1512360,188020017.0
36,https://m.media-amazon.com/images/M/MV5BMjA4ND...,The Prestige,2006,U,130,"Drama, Mystery, Sci-Fi",8.5,"After a tragic accident, two stage magicians e...",66.0,Christopher Nolan,Christian Bale,Hugh Jackman,Scarlett Johansson,Michael Caine,1190259,53089891.0
63,https://m.media-amazon.com/images/M/MV5BMTk4OD...,The Dark Knight Rises,2012,UA,164,"Action, Adventure",8.4,Eight years after the Joker's reign of anarchy...,78.0,Christopher Nolan,Christian Bale,Tom Hardy,Anne Hathaway,Gary Oldman,1516346,448139099.0
69,https://m.media-amazon.com/images/M/MV5BZTcyNj...,Memento,2000,UA,113,"Mystery, Thriller",8.4,A man with short-term memory loss attempts to ...,80.0,Christopher Nolan,Guy Pearce,Carrie-Anne Moss,Joe Pantoliano,Mark Boone Junior,1125712,25544867.0
155,https://m.media-amazon.com/images/M/MV5BOTY4Yj...,Batman Begins,2005,UA,140,"Action, Adventure",8.2,"After training with his mentor, Batman begins ...",70.0,Christopher Nolan,Christian Bale,Michael Caine,Ken Watanabe,Liam Neeson,1308302,206852432.0
573,https://m.media-amazon.com/images/M/MV5BN2YyZj...,Dunkirk,2017,UA,106,"Action, Drama, History",7.8,"Allied soldiers from Belgium, the British Empi...",94.0,Christopher Nolan,Fionn Whitehead,Barry Keoghan,Mark Rylance,Tom Hardy,555092,188373161.0

# Niveau 2 : Tri 

### Trouver les 10 films les mieux notés. 

### Trouver les 10 films les plus rentables. 

### Trouver les 20 films les plus récents. 

### Trouver le film le plus long. 
### Trouver le film le moins bien noté.

## Trouver les 10 films les mieux notés

In [16]:
movies.IMDB_Rating.dtype
movies.sort_values(by='IMDB_Rating', ascending=False).Series_Title.head(10)

0                         The Shawshank Redemption
1                                    The Godfather
4                                     12 Angry Men
2                                  The Dark Knight
3                           The Godfather: Part II
6                                     Pulp Fiction
7                                 Schindler's List
5    The Lord of the Rings: The Return of the King
9                                       Fight Club
8                                        Inception
Name: Series_Title, dtype: object

## Trouver les 10 films les plus rentables

In [17]:
movies.Gross.dtype
movies.sort_values(by='Gross', ascending=False).Series_Title.head(10)

477    Star Wars: Episode VII - The Force Awakens
59                              Avengers: Endgame
623                                        Avatar
60                         Avengers: Infinity War
652                                       Titanic
357                                  The Avengers
891                                 Incredibles 2
2                                 The Dark Knight
582                                     Rogue One
63                          The Dark Knight Rises
Name: Series_Title, dtype: object

## Trouver les 20 films les plus récents.

In [18]:
movies.Released_Year.dtype
movies.sort_values(by='Released_Year', ascending=False).Series_Title.head(20)

464                          Dil Bechara
612           The Trial of the Chicago 7
18                              Hamilton
20                       Soorarai Pottru
613                                 Druk
205                                 Soul
59                     Avengers: Endgame
128                           Chhichhore
484                         The Irishman
475                          Jojo Rabbit
585                         Little Women
195    Portrait de la jeune fille en feu
323                                 Togo
596                          Toy Story 4
91                  Miracle in cell NO.7
84                                  1917
33                                 Joker
334                            Gully Boy
135                                Klaus
882                           Just Mercy
Name: Series_Title, dtype: object

## Trouver le film le plus long.

In [19]:
movies.sort_values(by='Runtime', ascending=False).Series_Title.head(1)

#ou

movies.loc[movies.Runtime.idxmax()].Series_Title

'Gangs of Wasseypur'

## Trouver le film le moins bien noté.

In [20]:
movies.sort_values(by='IMDB_Rating').Series_Title.head(1)

985    Escape from Alcatraz
Name: Series_Title, dtype: object

# Niveau 3 : Valeurs manquantes 

### Combien de lignes contiennent au moins une valeur manquante ? 
### Quelle colonne contient le plus de valeurs manquantes ? 
### Remplacer les recettes manquantes par 0. 
### Afficher uniquement les films dont le Metascore est manquant.

## Combien de lignes contiennent au moins une valeur manquante ?

In [21]:
movies.isnull().any(axis=1).sum()

287

## Quelle colonne contient le plus de valeurs manquantes ?

In [23]:
movies.isnull().sum().idxmax()

'Gross'

## Remplacer les recettes manquantes par 0.

In [26]:
movies.Gross = movies.Gross.fillna(0)

## Afficher uniquement les films dont le Metascore est manquant.

In [27]:
movies[movies.Meta_score.isnull()]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
20,https://m.media-amazon.com/images/M/MV5BOTc2ZT...,Soorarai Pottru,2020,U,153,Drama,8.6,"Nedumaaran Rajangam ""Maara"" sets out to make t...",NaN,Sudha Kongara,Suriya,Madhavan,Paresh Rawal,Aparna Balamurali,54995,0.0
54,https://m.media-amazon.com/images/M/MV5BNWJhMD...,Ayla: The Daughter of War,2017,NaN,125,"Biography, Drama, History",8.4,"In 1950, amid-st the ravages of the Korean War...",NaN,Can Ulkay,Erdem Can,Çetin Tekindor,Ismail Hacioglu,Kyung-jin Lee,34112,0.0
55,https://m.media-amazon.com/images/M/MV5BY2FiMT...,Vikram Vedha,2017,UA,147,"Action, Crime, Drama",8.4,"Vikram, a no-nonsense police officer, accompan...",NaN,Gayatri,Pushkar,Madhavan,Vijay Sethupathi,Shraddha Srinath,28401,0.0
57,https://m.media-amazon.com/images/M/MV5BMTQ4Mz...,Dangal,2016,U,161,"Action, Biography, Drama",8.4,Former wrestler Mahavir Singh Phogat and his t...,NaN,Nitesh Tiwari,Aamir Khan,Sakshi Tanwar,Fatima Sana Shaikh,Sanya Malhotra,156479,12391761.0
65,https://m.media-amazon.com/images/M/MV5BMDhjZW...,Taare Zameen Par,2007,U,165,"Drama, Family",8.4,An eight-year-old boy is thought to be a lazy ...,NaN,Aamir Khan,Amole Gupte,Darsheel Safary,Aamir Khan,Tisca Chopra,168895,1223869.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
872,https://m.media-amazon.com/images/M/MV5BMTU5NT...,The Day the Earth Stood Still,1951,U,92,"Drama, Sci-Fi",7.7,An alien lands and tells the people of Earth t...,NaN,Robert Wise,Michael Rennie,Patricia Neal,Hugh Marlowe,Sam Jaffe,76315,0.0
874,https://m.media-amazon.com/images/M/MV5BYWUxMz...,Gilda,1946,Approved,110,"Drama, Film-Noir, Romance",7.7,A small-time gambler hired to work in a Buenos...,NaN,Charles Vidor,Rita Hayworth,Glenn Ford,George Macready,Joseph Calleia,27991,0.0
899,https://m.media-amazon.com/images/M/MV5BNGMxZj...,El cuerpo,2012,NaN,112,"Mystery, Thriller",7.6,A detective searches for the body of a femme f...,NaN,Oriol Paulo,Jose Coronado,Hugo Silva,Belén Rueda,Aura Garrido,57549,0.0
909,https://m.media-amazon.com/images/M/MV5BMjI2OD...,Celda 211,2009,NaN,113,"Action, Adventure, Crime",7.6,The story of two men on different sides of a p...,NaN,Daniel Monzón,Luis Tosar,Alberto Ammann,Antonio Resines,Manuel Morón,63882,0.0
913,https://m.media-amazon.com/images/M/MV5BMzc0Zm...,Die Welle,2008,NaN,107,"Drama, Thriller",7.6,A high school teacher's experiment to demonstr...,NaN,Dennis Gansel,Jürgen Vogel,Frederick Lau,Max Riemelt,Jennifer Ulrich,102742,0.0

# Niveau 4 : Groupby 

### Combien de films par année ? 

### Combien de films par réalisateur ? 

### Quelle est la note IMDb moyenne par réalisateur ? 

### Quelle est la note IMDb moyenne par genre ? 

### Quel réalisateur possède le plus de films dans le dataset ? 

### Quelle année possède la meilleure note moyenne ?

## Combien de films par année ?¶

In [172]:
movies.groupby('Released_Year').size()

Released_Year
1920     1
1921     1
1922     1
1924     1
1925     2
        ..
2016    28
2017    22
2018    19
2019    23
2020     6
Length: 99, dtype: int64

## Combien de films par réalisateur ?

In [28]:
movies.groupby('Director').size()

Director
Aamir Khan             1
Aaron Sorkin           1
Abdellatif Kechiche    1
Abhishek Chaubey       1
Abhishek Kapoor        1
                      ..
Zack Snyder            2
Zaza Urushadze         1
Zoya Akhtar            2
Çagan Irmak            1
Ömer Faruk Sorak       1
Length: 548, dtype: int64

## Quelle est la note IMDb moyenne par réalisateur ?

In [29]:
directors_mean = movies.groupby('Director').IMDB_Rating.mean()
directors_mean

Director
Aamir Khan             8.40
Aaron Sorkin           7.80
Abdellatif Kechiche    7.70
Abhishek Chaubey       7.80
Abhishek Kapoor        7.70
                       ...
Zack Snyder            7.60
Zaza Urushadze         8.20
Zoya Akhtar            8.05
Çagan Irmak            8.30
Ömer Faruk Sorak       8.00
Name: IMDB_Rating, Length: 548, dtype: float64

## Quelle est la note IMDB moyenne obtenue pas Christopher Nolan pour tous ses films

In [30]:
directors_mean.loc['Christopher Nolan']

8.4625

## Quelle est la note IMDb moyenne par genre ?

In [31]:
genre_mean = movies.groupby('Genre').IMDB_Rating.mean()
genre_mean

Genre
Action, Adventure               8.180000
Action, Adventure, Biography    7.900000
Action, Adventure, Comedy       7.910000
Action, Adventure, Crime        7.600000
Action, Adventure, Drama        8.150000
                                  ...
Mystery, Romance, Thriller      8.300000
Mystery, Sci-Fi, Thriller       7.800000
Mystery, Thriller               7.977778
Thriller                        7.800000
Western                         8.350000
Name: IMDB_Rating, Length: 202, dtype: float64

## Quel réalisateur possède le plus de films dans le dataset ?

In [32]:
best_director = movies.groupby('Director').size().idxmax()
best_director

'Alfred Hitchcock'

## Quelle année possède la meilleure note moyenne ?

In [33]:
best_year = movies.groupby('Released_Year').IMDB_Rating.mean().idxmax()
best_year

1936

# Niveau 5 : Value Counts 

### Quels sont les genres les plus fréquents ? 

### Quels sont les 10 réalisateurs les plus présents ? 

### Quelle année apparaît le plus souvent ?

### Quels sont les genres les plus fréquents ?

In [34]:
movies.Genre.value_counts().idxmax()

'Drama'

## Quels sont les 10 réalisateurs les plus présents ?

In [35]:
movies.Director.value_counts().head(10).index

Index(['Alfred Hitchcock', 'Steven Spielberg', 'Hayao Miyazaki',
       'Akira Kurosawa', 'Martin Scorsese', 'Billy Wilder', 'Woody Allen',
       'Stanley Kubrick', 'Clint Eastwood', 'David Fincher'],
      dtype='object', name='Director')

## Quelle année apparaît le plus souvent ?¶

In [36]:
movies.Released_Year.value_counts().idxmax()

2014

# Niveau 6 : Création de colonnes 

### Créer une colonne indiquant si un film est : Court (< 90 min) Moyen (90-120 min) Long (> 120 min) 

### Créer une colonne "Décennie". 

### Créer une colonne indiquant si un film est "Très bien noté" (IMDb ≥ 8).

## Créer une colonne indiquant si un film est : Court (< 90 min) Moyen (90-120 min) Long (> 120 min)

In [37]:
def timing(time) :
    if time < 90 :
        return "Court"
    elif time <= 120 :
        return "Moyen"
    else :
        return "Long"
    
movies['Timing'] = movies.Runtime.apply(timing)
movies.Timing

0       Long
1       Long
2       Long
3       Long
4      Moyen
       ...
995    Moyen
996     Long
997    Moyen
998    Moyen
999    Court
Name: Timing, Length: 1000, dtype: object

## Créer une colonne "Décennie".

In [38]:
def convert_decade(year) :
    x = year // 10
    x = x * 10
    return x

movies['Decade'] = movies.Released_Year.apply(convert_decade)
movies.Decade

0      1990
1      1970
2      2000
3      1970
4      1950
       ...
995    1960
996    1950
997    1950
998    1940
999    1930
Name: Decade, Length: 1000, dtype: object

## Créer une colonne indiquant si un film est "Très bien noté" (IMDb ≥ 8).

In [39]:
movies['Is_Good'] = movies.IMDB_Rating.apply(lambda x : x>=8)
movies.Is_Good

0       True
1       True
2       True
3       True
4       True
       ...
995    False
996    False
997    False
998    False
999    False
Name: Is_Good, Length: 1000, dtype: bool

# Niveau 7 : MultiIndex 

### Combien de films par année et par genre ? 

### Quelle est la note moyenne par année et par réalisateur ? 

### Quel genre domine chaque décennie ?

## Combien de films par année et par genre ?

In [40]:
# On calcule votre regroupement
resultat = movies.groupby(['Released_Year', 'Genre']).size()

# On force l'affichage de TOUTES les lignes (max_rows=None)
with pd.option_context('display.max_rows', None):
    print(resultat)

Released_Year  Genre
1920           Fantasy, Horror, Mystery         1
1921           Comedy, Drama, Family            1
1922           Fantasy, Horror                  1
1924           Action, Comedy, Romance          1
1925           Adventure, Comedy, Drama         1
               Drama, History, Thriller         1
1926           Action, Adventure, Comedy        1
1927           Drama, Romance                   1
               Drama, Sci-Fi                    1
1928           Biography, Drama, History        1
               Comedy, Romance                  1
1930           Drama, War                       1
1931           Comedy, Drama, Romance           1
               Crime, Mystery, Thriller         1
               Drama, Horror, Sci-Fi            1
1932           Action, Crime, Drama             1
               Drama, Horror                    1
1933           Adventure, Horror, Sci-Fi        1
               Comedy, Musical, War             1
               Horror, Sci-Fi                   1
1934           Comedy, Crime, Mystery           1
               Comedy, Romance                  1
1935           Comedy, Music, Musical           1
               Crime, Mystery, Thriller         1
               Drama, Horror, Sci-Fi            1
1936           Comedy, Drama, Family            1
1937           Drama, War                       1
1938           Action, Adventure, Romance       1
               Comedy, Family, Romance          1
               Mystery, Thriller                1
1939           Adventure, Drama, Western        1
               Adventure, Family, Fantasy       1
               Comedy, Drama                    2
               Drama, History, Romance          1
1940           Animation, Family, Fantasy       1
               Comedy, Drama, Romance           2
               Comedy, Drama, War               1
               Comedy, Romance                  1
               Drama, History                   1
               Drama, Mystery, Romance          1
1941           Drama, Mystery                   1
               Film-Noir, Mystery               1
1942           Comedy, Crime, Thriller          1
               Comedy, War                      1
               Drama, Romance, War              1
1943           Film-Noir, Thriller              1
1944           Adventure, Comedy, Film-Noir     1
               Crime, Drama, Film-Noir          1
               Drama, Film-Noir, Mystery        1
               Drama, War                       1
1945           Drama, Film-Noir                 1
               Drama, Romance                   1
1946           Crime, Film-Noir, Mystery        1
               Drama, Family, Fantasy           1
               Drama, Film-Noir, Romance        2
               Drama, Romance, War              1
1947           Comedy, Drama, Family            1
               Crime, Drama, Film-Noir          1
1948           Action, Adventure, Drama         1
               Action, Crime, Drama             1
               Adventure, Drama, Western        1
               Crime, Drama, Mystery            1
               Drama                            1
               Drama, Music, Romance            1
1949           Action, Crime, Drama             1
               Comedy, Crime                    1
               Film-Noir, Mystery, Thriller     1
1950           Comedy, Drama, Fantasy           1
               Crime, Drama, Mystery            1
               Drama                            1
               Drama, Film-Noir                 1
               Drama, Film-Noir, Mystery        1
1951           Adventure, Drama, Romance        1
               Crime, Film-Noir, Thriller       1
               Drama                            1
               Drama, Film-Noir                 1
               Drama, Sci-Fi                    1
1952           Comedy, Drama, Romance           1
               Comedy, Musical, Romance         1
               Drama                            1
               Drama, Thriller, Western         1
1953           Adventure, Drama, Thriller       1
               Comedy, Drama, War               1
               Comedy, Romance                  1
               Drama                            1
               Drama, Romance, War              1
1954           Action, Adventure, Drama         1
               Comedy, Drama, Romance           1
               Crime, Drama, Thriller           1
               Crime, Thriller                  1
               Drama                            1
               Mystery, Thriller                1
1955           Comedy, Crime                    1
               Crime, Drama, Film-Noir          1
               Crime, Drama, Horror             1
               Crime, Drama, Thriller           1
               Drama                            2
1956           Adventure, Drama                 1
               Adventure, Drama, Western        1
               Crime, Drama, Film-Noir          1
               Drama, Horror, Sci-Fi            1
               Drama, Western                   1
1957           Adventure, Drama, War            1
               Crime, Drama                     1
               Crime, Drama, Mystery            1
               Drama                            1
               Drama, Fantasy, History          1
               Drama, Film-Noir                 1
               Drama, History                   1
               Drama, Romance                   1
               Drama, War                       1
1958           Adventure, Drama                 1
               Crime, Drama, Film-Noir          1
               Drama                            1
               Mystery, Romance, Thriller       1
1959           Action, Drama, Western           1
               Adventure, Drama, History        1
               Adventure, Mystery, Thriller     1
               Comedy, Music, Romance           1
               Crime, Drama                     1
               Crime, Drama, Mystery            1
               Drama, Romance                   1
1960           Action, Adventure, Western       1
               Adventure, Biography, Drama      1
               Biography, Drama, History        1
               Comedy, Drama                    1
               Comedy, Drama, Romance           1
               Crime, Drama                     1
               Drama                            1
               Drama, Horror                    1
               Drama, Horror, Thriller          1
               Drama, Mystery                   1
               Horror, Mystery, Thriller        1
1961           Action, Drama, Thriller          1
               Comedy, Drama, Romance           1
               Drama, Sport                     1
               Drama, War                       1
               Horror                           1
1962           Action, Comedy, Crime            1
               Action, Drama, History           1
               Action, Drama, Mystery           1
               Adventure, Biography, Drama      1
               Crime, Drama                     1
               Drama                            1
               Drama, Fantasy                   1
               Drama, Horror, Thriller          1
               Drama, Romance                   1
               Drama, Thriller                  2
               Drama, War                       1
               Drama, Western                   1
1963           Adventure, Drama, History        1
               Comedy, Mystery, Romance         1
               Crime, Drama, Mystery            1
               Drama                            1
               Drama, Horror, Mystery           1
1964           Action, Adventure, Thriller      1
               Action, Drama, Western           1
               Comedy                           1
               Comedy, Family, Fantasy          1
               Comedy, Music, Musical           1
               Drama, Family, Musical           1
               Drama, History, War              1
1965           Biography, Drama, Family         1
               Drama, Horror, Thriller          1
               Drama, Romance, War              1
               Western                          1
1966           Biography, Drama, History        2
               Drama                            1
               Drama, Mystery, Thriller         1
               Drama, Thriller                  1
               Drama, War                       1
               Western                          1
1967           Action, Adventure, War           1
               Action, Biography, Crime         1
               Animation, Adventure, Family     1
               Comedy, Drama                    1
               Comedy, Drama, Romance           1
               Crime, Drama                     1
               Crime, Drama, Mystery            2
               Drama, Romance                   1
               Thriller                         1
1968           Action, Adventure, War           1
               Adventure, Sci-Fi                2
               Biography, Drama, History        1
               Comedy                           1
               Drama, Horror                    1
               Horror, Thriller                 1
               Western                          1
1969           Action, Adventure, Western       1
               Biography, Crime, Drama          1
               Drama                            1
1970           Adventure, Comedy, War           1
               Biography, Drama, War            1
               Drama                            1
1971           Action, Crime, Drama             1
               Action, Crime, Thriller          1
               Comedy, Drama, Romance           1
               Crime, Drama, Sci-Fi             1
               Drama, Family, Musical           1
               Drama, Musical                   1
               Drama, Romance                   1
               Drama, War, Western              1
               Family, Fantasy, Musical         1
1972           Action, Adventure, Biography     1
               Adventure, Drama, Thriller       1
               Comedy                           1
               Crime, Drama                     1
               Drama                            1
               Drama, Music, Musical            1
               Drama, Mystery, Sci-Fi           1
               Mystery, Thriller                1
1973           Action, Crime, Drama             2
               Adventure, Drama, Fantasy        1
               Animation, Sci-Fi                1
               Biography, Crime, Drama          2
               Comedy, Crime, Drama             3
               Comedy, Drama, Family            1
               Crime, Drama, Thriller           1
               Horror                           1
1974           Action, Crime, Thriller          1
               Comedy                           1
               Comedy, Western                  1
               Crime, Drama                     1
               Drama, Mystery, Thriller         2
1975           Action, Adventure, Comedy        1
               Adventure, Comedy, Fantasy       1
               Adventure, Drama, History        1
               Adventure, History, War          1
               Adventure, Thriller              1
               Biography, Crime, Drama          1
               Biography, Drama                 1
               Comedy, War                      1
               Drama                            1
1976           Biography, Drama, History        2
               Crime, Drama                     1
               Drama                            1
               Drama, Sport                     1
               Drama, Thriller                  1
               Western                          1
1977           Action, Adventure, Fantasy       1
               Comedy, Romance                  1
               Drama, Sci-Fi                    1
1978           Action, Adventure, Horror        1
               Animation, Adventure, Drama      1
               Biography, Crime, Drama          1
               Drama, Music                     1
               Drama, Romance                   1
               Drama, War                       1
               Horror, Thriller                 1
1979           Action, Biography, Crime         1
               Action, Crime, Thriller          1
               Adventure, Comedy, Family        1
               Animation, Adventure, Family     1
               Comedy                           1
               Comedy, Drama                    1
               Comedy, Drama, Romance           1
               Drama                            1
               Drama, Music, Musical            1
               Drama, Mystery, War              1
               Drama, Sci-Fi                    1
               Horror, Sci-Fi                   1
1980           Action, Adventure, Comedy        1
               Action, Adventure, Fantasy       1
               Biography, Drama                 1
               Biography, Drama, Sport          1
               Comedy                           1
               Drama                            1
               Drama, History, War              1
               Drama, Horror                    1
1981           Action, Adventure                1
               Action, Adventure, Sci-Fi        1
               Adventure, Drama, Thriller       1
               Drama                            1
1982           Action, Adventure                1
               Action, Adventure, Sci-Fi        1
               Action, Sci-Fi, Thriller         1
               Adventure, Drama                 1
               Biography, Drama, History        1
               Comedy, Crime, Drama             1
               Drama                            2
               Drama, Fantasy, Music            1
               Family, Sci-Fi                   1
               Horror, Mystery, Sci-Fi          1
1983           Action, Adventure, Fantasy       1
               Adventure, Biography, Drama      1
               Comedy                           1
               Comedy, Family                   1
               Crime, Drama                     1
1984           Action, Comedy, Fantasy          1
               Action, Sci-Fi                   1
               Animation, Adventure, Fantasy    1
               Biography, Drama, History        2
               Comedy, Music                    1
               Crime, Drama                     1
               Crime, Drama, Thriller           1
               Drama                            1
1985           Action, Drama, War               1
               Adventure, Comedy, Family        1
               Adventure, Comedy, Sci-Fi        1
               Comedy, Crime, Drama             1
               Comedy, Drama                    1
               Comedy, Fantasy, Romance         1
               Drama                            1
               Drama, Sci-Fi                    1
               Drama, Thriller, War             1
1986           Action, Adventure, Sci-Fi        1
               Adventure, Drama                 1
               Animation, Adventure, Drama      1
               Comedy                           1
               Comedy, Crime, Drama             1
               Comedy, Drama                    1
               Crime, Drama, Mystery            1
               Drama, Mystery, Thriller         1
               Drama, War                       1
1987           Action, Adventure, Sci-Fi        1
               Action, Comedy, Fantasy          1
               Action, Crime, Thriller          1
               Action, Drama, History           1
               Adventure, Family, Fantasy       1
               Biography, Drama, History        1
               Comedy, Drama                    2
               Crime, Drama, Thriller           1
               Drama, Fantasy, Romance          1
               Drama, War                       2
1988           Action, Thriller                 1
               Animation, Action, Sci-Fi        1
               Animation, Adventure, Comedy     1
               Animation, Drama, War            1
               Animation, Family, Fantasy       1
               Comedy, Crime                    1
               Comedy, Crime, Drama             1
               Crime, Drama, History            1
               Drama                            1
               Drama, Romance                   1
               Mystery, Thriller                1
1989           Action, Adventure                1
               Action, Crime, Drama             1
               Adventure, Comedy, Sci-Fi        1
               Animation, Adventure, Drama      1
               Animation, Family, Fantasy       1
               Biography, Drama                 1
               Biography, Drama, History        1
               Comedy, Drama                    3
               Comedy, Drama, Romance           1
1990           Adventure, Drama, Western        1
               Biography, Crime, Drama          1
               Biography, Drama                 1
               Comedy, Family                   1
               Crime, Drama                     1
               Crime, Drama, Thriller           1
               Drama, Fantasy, Romance          1
               Drama, Thriller                  1
1991           Action, Sci-Fi                   1
               Animation, Drama, Romance        1
               Animation, Family, Fantasy       1
               Comedy, Crime                    1
               Comedy, Drama                    1
               Comedy, Drama, Thriller          1
               Crime, Drama                     1
               Crime, Drama, Thriller           1
               Drama                            1
               Drama, Fantasy, Music            1
               Drama, History, Romance          1
               Drama, History, Thriller         1
1992           Action, Adventure, Drama         1
               Action, Crime, Thriller          1
               Animation, Adventure, Comedy     2
               Biography, Drama, History        1
               Comedy, Crime                    1
               Comedy, Drama, Family            1
               Crime, Drama, Mystery            1
               Crime, Drama, Thriller           1
               Drama                            1
               Drama, Thriller                  1
               Drama, Western                   1
1993           Action, Adventure, Sci-Fi        1
               Action, Biography, Drama         1
               Action, Crime, Drama             2
               Animation, Action, Adventure     1
               Animation, Action, Crime         1
               Animation, Family, Fantasy       1
               Biography, Crime, Drama          1
               Biography, Drama, History        1
               Comedy                           1
               Comedy, Drama                    2
               Comedy, Drama, Family            1
               Comedy, Fantasy, Romance         1
               Crime, Drama                     1
               Crime, Drama, Romance            2
               Crime, Drama, Thriller           1
               Drama                            2
               Drama, Music, Mystery            1
               Drama, Music, Romance            1
               Drama, Romance                   1
1994           Action, Comedy, Romance          1
               Action, Crime, Drama             1
               Animation, Adventure, Drama      1
               Biography, Comedy, Drama         2
               Comedy                           1

## Quelle est la note moyenne par année et par réalisateur ?

In [41]:
movies.groupby(['Released_Year', 'Director']).IMDB_Rating.mean()

Released_Year  Director
1920           Robert Wiene         8.1
1921           Charles Chaplin      8.3
1922           F.W. Murnau          7.9
1924           Buster Keaton        8.2
1925           Charles Chaplin      8.2
                                   ...
2020           Mukesh Chhabra       7.9
               Pete Docter          8.1
               Sudha Kongara        8.6
               Thomas Kail          8.6
               Thomas Vinterberg    7.8
Name: IMDB_Rating, Length: 989, dtype: float64

## Quel genre domine chaque décennie ?

In [51]:
#movies.groupby(['Decade', 'Genre']).size().idxmax()[1]
genre_dominant = movies.groupby(['Decade', 'Genre']).size().idxmax()
genre_dominant[1]
#movies

'Drama'

# Niveau 8 : Réflexion 

### Les critiques (Metascore) sont-elles généralement plus sévères que les utilisateurs (IMDb) ? 

### Les films longs sont-ils mieux notés que les films courts ? 

### Les réalisateurs avec beaucoup de films obtiennent-ils de meilleures notes en moyenne ? 

### Certaines décennies produisent-elles davantage de films bien notés ? 

### Les combinaisons de genres les plus fréquents sont-il aussi les mieux notés ?

In [43]:
movies

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Timing,Decade,Is_Good
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469.0,Long,1990,True
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,134966411.0,Long,1970,True
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444.0,Long,2000,True
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,57300000.0,Long,1970,True
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,4360000.0,Moyen,1950,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,0.0,Moyen,1960,False
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,0.0,Long,1950,False
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,30500000.0,Moyen,1950,False
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,0.0,Moyen,1940,False
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,0.0,Court,1930,False

## Les critiques (Metascore) sont-elles généralement plus sévères que les utilisateurs (IMDb) ?

In [44]:
moyenne_Meta_score = movies.Meta_score.mean()
moyenne_IMDB_Rating = movies.IMDB_Rating.mean() * 10

if(moyenne_Meta_score > moyenne_IMDB_Rating) :
    print("Oui les critiques Metascore sont plus séveres que les utilisateurs IMDB")
elif(moyenne_Meta_score < moyenne_IMDB_Rating) :
    print("Non les critiques Metascore ne sont pas plus séveres que les utilisateurs IMDB")
else :
    print("Les critiques Metascore et les utilisateurs IMDB ont donnés les meme notes")

Non les critiques Metascore ne sont pas plus séveres que les utilisateurs IMDB

## Les films longs sont-ils mieux notés que les films courts ?

In [45]:
notes_films_longs = movies[movies.Timing == "Long"].IMDB_Rating.mean()
notes_films_courts = movies[movies.Timing == "Court"].IMDB_Rating.mean()

if(notes_films_longs > notes_films_courts) :
    print("Oui les films long sont mieux notés que les films courts")
elif(notes_films_longs < notes_films_courts) :
    print("Non les films courts sont mieux notés ue les films long")
else :
    print("Les films courts et les films long ont les meme notes")

Oui les films long sont mieux notés que les films courts

## Les réalisateurs avec beaucoup de films obtiennent-ils de meilleures notes en moyenne ?

In [47]:
#On cré une data frame dans laquelle se trouve les réalisateurs,
#le nombre de films de chaque réalisateurs et la note moyenne 
#obtenue par chaque réalisateur pour leurs films

movies_directors_stats = movies.groupby('Director').agg(
    Nb_Films=('Director', 'size'),
    Note_Moyenne=('IMDB_Rating', 'mean')
)

movies_directors_stats.sort_values(by='Nb_Films', ascending=False)

#On cherche le nombre de réalisateurs ayant réalisé au moins 5 films
beaucoup = movies_directors_stats[movies_directors_stats.Nb_Films >= 5]

#On cherche le nombre de réalisateur ayant réalisé au plus 4 films
peu = movies_directors_stats[movies_directors_stats.Nb_Films < 5]

#Moyenne des notes moyennes de beaucoup
moyenne_beaucoup = beaucoup.Note_Moyenne.mean()

#Moyenne de peu
moyenne_peu = peu.Note_Moyenne.mean()

if(moyenne_beaucoup > moyenne_peu) :
    print("Les réalisateurs ayant réalisé le plus de film on obtenu de meilleurs notes en moyenne")
elif(moyenne_beaucoup < moyenne_peu) :
    print("Les réalisateur ayant réalisé le moins de film ont obtenu de meilleurs notes en moyenne")
else :
    print("Les réalisateurs ayant réalisé le moins de film et le plus de films ont la meme note moyenne")

Les réalisateurs ayant réalisé le plus de film on obtenu de meilleurs notes en moyenne

## Certaines décennies produisent-elles davantage de films bien notés ?

In [48]:
#On cré une fonction qui calcule la fréquence ne pourcentage
def freq(effectif, effectif_total) :
    return (effectif/effectif_total)*100

#On crée une data frame contenant les decenies, le nombre de films
#par décenies et le nombre de bons films par décenies

movies_decenies_stats = movies.groupby('Decade').agg(
    Nb_Films_Decenies=('Decade', 'size'),
    Nb_Bon_Films_Decenies=('Is_Good', 'sum')
)
movies_decenies_stats

#On cré une colone Fréquence
movies_decenies_stats['Frequences'] = freq(
    movies_decenies_stats['Nb_Bon_Films_Decenies'], 
    movies_decenies_stats['Nb_Films_Decenies'])

movies_decenies_stats.sort_values(by='Frequences', ascending=False)

#On cherche les  premieres decenies ayant produits d'avantages
#de films bien notés
movies_decenies_stats.head(5)

#Une question se pose :  Es ce qu'une decenie ayant 90% de bon film
#mais avec 10 bons films sur 11 films; est meilleure qu'une decenie
#ayant 71% de bon films mais avec 40 bon films sur 56 films?

        Nb_Films_Decenies  Nb_Bon_Films_Decenies  Frequences
Decade
1920                   11                     10   90.909091
1930                   24                     11   45.833333
1940                   35                     22   62.857143
1950                   56                     40   71.428571
1960                   73                     38   52.054795

## Les combinaisons de genres les plus fréquents sont-il aussi les mieux notés ?

In [58]:
#On cherche le genre le mieux noté
best_genre = movies.groupby('Genre').IMDB_Rating.mean().idxmax()

#On cherche le genre le plus fréquent
max_genre = movies.Genre.value_counts().idxmax()

if(max_genre == best_genre) :
    print("Oui le genre le plus fréquent est aussi le mieux noté")
else :
    print("Non le genre le plus fréquent n'est pas le mieux noté")

max_genre
best_genre

Non le genre le plus fréquent n'est pas le mieux noté

'Animation, Drama, War'